#include "headfile.h"


void System_Halt(void)//待机模式 halt1
{
    LPMODE->MODE = 0;
    NOP;NOP;NOP;
    wfi();
    NOP;NOP;NOP;
}

void System_Sleep(void)//睡眠模式 halt2
{
    LPMODE->MODE = 1;
    NOP;NOP;NOP;
    wfi();
    NOP;NOP;NOP;
}

void System_Powerdown(void)//掉电模式 powerdown1
{

    /*set the internal voltage when in powerdown1 mode*/
    /*
    uint32_t temp = ANA->CFG1;
    uint32_t ldo_set = 1; //internal ldo set: 0-level_0, 1-level_1, 2-level_2, 3-level_3
    temp &= 0x9fffffff;
    temp |= (ldo_set&0x3)<<29;
    ANA->CFG1 = temp;
    */


    LPMODE->MODE = 2;
    NOP;NOP;NOP;
    wfi();
    NOP;NOP;NOP;
}

void System_DeepPwd(void)//掉电模式 powerdown2
{
    LPMODE->MODE = 3;
    NOP;NOP;NOP;
    wfi();
    NOP;NOP;NOP;
}



void LowPower_Config_case1(void)//所有IO设置为输入，下拉
{
    GPIO_MODE_Init(GPIOA,PIN0,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN1,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN2,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN3,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN4,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN5,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN6,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN7,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN8,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN9,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN10,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN11,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN12,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN13,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN14,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN15,GPIO_MODE_INPUT);

    GPIO_PULL_Init(GPIOA, PIN0,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN1,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN2,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN3,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN4,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN5,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN6,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN7,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN8,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN9,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN10,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN11,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN12,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN13,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN14,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOA, PIN15,GPIO_PULLDOWN);

    GPIO_MODE_Init(GPIOB,PIN0,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN1,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN2,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN3,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN4,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN5,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN6,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN7,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN8,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN9,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN10,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN11,GPIO_MODE_INPUT);

    GPIO_PULL_Init(GPIOB, PIN0,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN1,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN2,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN3,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN4,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN5,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN6,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN7,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN8,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN9,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN10,GPIO_PULLDOWN);
    GPIO_PULL_Init(GPIOB, PIN11,GPIO_PULLDOWN);
}



void LowPower_Config_case2(void)//所有IO设置为输入，上拉
{
    GPIO_MODE_Init(GPIOA,PIN0,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN1,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN2,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN3,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN4,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN5,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN6,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN7,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN8,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN9,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN10,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN11,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN12,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN13,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN14,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOA,PIN15,GPIO_MODE_INPUT);

    GPIO_PULL_Init(GPIOA, PIN0,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN1,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN2,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN3,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN4,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN5,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN6,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN7,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN8,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN9,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN10,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN11,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN12,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN13,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN14,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOA, PIN15,GPIO_PULLUP);

    GPIO_MODE_Init(GPIOB,PIN0,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN1,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN2,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN3,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN4,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN5,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN6,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN7,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN8,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN9,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN10,GPIO_MODE_INPUT);
    GPIO_MODE_Init(GPIOB,PIN11,GPIO_MODE_INPUT);

    GPIO_PULL_Init(GPIOB, PIN0,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN1,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN2,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN3,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN4,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN5,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN6,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN7,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN8,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN9,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN10,GPIO_PULLUP);
    GPIO_PULL_Init(GPIOB, PIN11,GPIO_PULLUP);
}

